# Generated by Django 5.1.7 on 2025-03-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dekkway_app', '0001_initial'),
    ]

    operations = [
         migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS unaccent;"
            "CREATE TEXT SEARCH CONFIGURATION french_unaccent ( COPY = french );"
            "ALTER TEXT SEARCH CONFIGURATION french_unaccent ALTER MAPPING "
            "FOR hword, hword_part, word WITH unaccent, french_stem;",
            reverse_sql="DROP EXTENSION unaccent;"
        )
    ]
