# Generated by Django 5.1.7 on 2025-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dekkway_app', '0002_enable_postgres_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
