# Generated by Django 5.1.7 on 2025-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dekkway_app', '0004_remove_logement_medias_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='titre',
            field=models.CharField(default='essaie logement', max_length=255, verbose_name='Titre du logement'),
            preserve_default=False,
        ),
    ]
