# Generated by Django 5.1.7 on 2025-04-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dekkway_app', '0005_logement_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='cuisines',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de cuisines'),
        ),
        migrations.AddField(
            model_name='logement',
            name='garage',
            field=models.BooleanField(default=False, verbose_name="Présence d'un garage"),
        ),
        migrations.AddField(
            model_name='logement',
            name='salles_de_bain',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de salles de bain'),
        ),
        migrations.AddField(
            model_name='logement',
            name='salons',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de salons'),
        ),
    ]
