# Generated by Django 5.1.7 on 2025-04-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dekkway_app', '0006_logement_cuisines_logement_garage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.FileField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
