# Generated by Django 5.1.7 on 2025-04-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dekkway_app', '0007_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='duree',
            field=models.CharField(choices=[('longue durée', 'Longue durée'), ('courte durée', 'Courte durée')], default='longue durée', max_length=20, verbose_name='Durée de location'),
        ),
    ]
